title: "CAESAR: Causal Anomalies - Exploring Synergies of Anomaly Detection and Causal Inference"
description: "Workshop on causal inference, anomaly detection, their intersection and borders"

lang: en
theme: jekyll-theme-cayman
#plugins:
#  - jekyll-remote-theme
# IMPORTANT:
# - For GitHub project pages: baseurl: "/REPO_NAME"
# - For GitHub user/org pages (USERNAME.github.io): baseurl: ""
# - For GitLab pages: baseurl: "/REPO_NAME"
url: ""

baseurl: "/"


include:
  - assets